### ISSUE TITLE
Zbudowanie szkieletu aplikacji

### ISSUE THREAD

**Issue by emsi93** [conehow/Blue-Steenbok-BE#3]
Zbudować szkielet aplikacji z wykorzystaniem kotlina i springa (spring boot, spring data).

Projekt ma być tak zbudowany aby można go było odpalić na każdym środowisku, systemie.
Aplikacja ma zawierać podłączenie do bazy, w taki sposób aby można było je łatwo skonfigurować.
Pozwoli to nam w przyszłości na łatwą zmianę podłączenia (zmiana urli, driverow, userów i passwordów).

Dodatkowo napisać prostą usługę restową echo, razem z testami.

**Comment by gtwsky** [comment]
Zadanie powstało jako sprecyzowanie dyskusji z #1

**Comment by gtwsky** [comment]
Kilka uwag jakie mi się nasuneły:
> Aplikacja ma zawierać podłączenie do bazy, w taki sposób aby można było je łatwo skonfigurować.
Nie oznacza to, że już na samym początku musi być implementacja. Same dobrze zdefiniowane interfejsy starczą. Dzieki temu bedzie mozna juz jakos _popodłączać_ kod. Implementacją baz będzie kolejnymi taskami.

Dodatkowo nie zapomnij aby dodać konfigurację Dockera, lepiej to zrobić na początku bo potem (jak dobrze wiemy ;)) będzie problem.

**Comment by emsi93** [comment]
Stworzyłem szkielet aplikacji. Aplikacja jest budowana przy użyciu mavena. Krótko opiszę co zrobiłem, czego nie:

Skonfigurowane jest podłączenie do bazy MySQL, na tę chwile tak zrobiłem ponieważ chciałem przetestować encje, repository (spring data). 
Napisałem usługę echo (localhost:8080/blue-steenbok/echo?message=value) i do niej test.
Jakość kodu Kotlina nie jest może najlepsza, tez nie ma go dużo ale wraz z nauką powinna rosnąć.
Na tę chwilę nie ma skonfigurowanego jeszcze dockera. 
Instrukcja uruchomienia aplikacji znajduje się w pliku instruction.txt

Możesz zrobić jakiś wstępny code review, zadanie dopiero bede mergował jak skończe konfiguracje dockera.

Ps. Co do bazy, zostawiamy tego MySQL(do testów) czy przy okazji dockera mam zmienić ją na H2?

Config DB:
user = root
password = praktyka
SQL: create database mockapp;

**Comment by emsi93** [comment]
Dodatkowo logi aplikacji zapisują się w folderze logs/.

**Comment by emsi93** [comment]
poprawiłem strukture projektu, wyglada teraz tak jak to ustalilismy wczesniej,
podpiąłem h2,
poprawiłem testy, dzialaja teraz jak nalezy

został do zrobienia docker

**WAZNE**
Teraz usługa wystawiona jest na localhost:8080/steenbok/echo?message=value

**Comment by emsi93** [comment]
Problem z dockerem, docker nie dziala pod windows 10 home dlatego mam problem z uruchomieniem go.

Poprawie strukture projektu poprzez dodanie serwisow i merguje taska a docker będzie oddzielnym taskiem

**Comment by gtwsky** [comment]
W ramach tego taska wykonany jest również #6

**Comment by emsi93** [comment]
skończone
