### ISSUE TITLE
Konfiguracja dockera

### ISSUE THREAD

**Issue by emsi93** [conehow/Blue-Steenbok-BE#6]
Skonfigurowac dockera z backendem (docker + spring boot)

Uwaga nie dziala na windows 10 home

**Comment by emsi93** [comment]
docker dziala na ubuntu, odpalilem wszystko na maszynie, skonfigurowalem pierwsza wersje dockerfile.

Uwaga przez przypadek w zmiany sa w branchu 3.

**Comment by gtwsky** [comment]
Fajnie że udało ci się ogarnąć dockera na kompie w jakiś sposób. Mam kilka pytań:

pom.xml:26 - <docker.image.prefix>springio</docker.image.prefix> Co to spring.io?

dockerfile:4 - Jak kopiujesz pliki do image'a, używaj COPY, bo ADD działa jeszcze na wiele innych formatów.

Fajnie by było jakby ten task był osobnym branchem, ale już żeby nie robić dymów połącze ten task z taskiem 3 jako podtask.

Skoro działa, to prosze popraw te kilka uwag albo je wyjaśnij i możesz mergować do mastera.

**Comment by emsi93** [comment]
skończone
